# site settings
title: Patrick Despres-Gallagher
email: pjdgallagher@gmail.com
description: 
baseurl: "/pjdgallagher" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Patrick Despres-Gallagher

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings
instagram_url: https://instagram.com/pjdgallagher
linkedin_url: https://www.linkedin.com/in/pjdgallagher
twitter_url: https://twitter.com/pjdgallagher
github_url: https://github.com/u/pjdgallagher

# build settings
markdown: kramdown

sass:
  style: compressed
